---
# tasks file for roles/app
- name: Run Backend API
  docker_container:
    name: student-api
    image: lauradmsefrei/tp-devops-simple-api:latest
    networks:
      - name: app-network
    ports:
      - "8080:8080"
    env:
      DATABASE_URL: "database_postgres" # Le nom du conteneur DB sert de host
    restart_policy: always
  # vars:
  #   ansible_python_interpreter: /opt/docker_venv/bin/python