# Utilisation d'une image maintenue et légère
#FROM amazoncorretto:17-alpine

# Dossier de travail
#WORKDIR /app

# Copie du bytecode (le .class généré avec javac)
#COPY Main.class .

# Lancement
#CMD ["java", "Main"]

